name: Build test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PREFIX=$HOME/.local/bin
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        mkdir -p $PREFIX
        make
    - name: Run install
      run: make install

