name: Build test
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PREFIX: $HOME/.local/bin
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        mkdir -p $PREFIX
        make
    - name: Run install
      run: make uninstall && make install

